In [1]:
#Import pandas to do data cleaning
import pandas as pd

In [2]:
#Load dataset and have a quick look at the first few rows
df=pd.read_excel("Unemployment_COPY.xlsx",sheet_name=0)
df.head()

,FIPS_Code,State,Area_Name,Rural_Urban_Continuum_Code_2013,Urban_Influence_Code_2013,Metro_2013,Civilian_labor_force_2000,Employed_2000,Unemployed_2000,Unemployment_rate_2000,...,Civilian_labor_force_2021,Employed_2021,Unemployed_2021,Unemployment_rate_2021,Civilian_labor_force_2022,Employed_2022,Unemployed_2022,Unemployment_rate_2022,Median_Household_Income_2021,Med_HH_Income_Percent_of_State_Total_2021
0,0,US,United States,NaN,NaN,NaN,142601576.0,136904853.0,5696723.0,4.0,...,162229903.0,153544980.0,8684923.0,5.4,164781642.0,158766998.0,6014644.0,3.7,69717.0,NaN
1,1000,AL,Alabama,NaN,NaN,NaN,2147173.0,2047731.0,99442.0,4.6,...,2259349.0,2183330.0,76019.0,3.4,2286028.0,2226670.0,59358.0,2.6,53990.0,100.0
2,1001,AL,"Autauga County, AL",2.0,2.0,1.0,21861.0,20971.0,890.0,4.1,...,26545.0,25809.0,736.0,2.8,26789.0,26181.0,608.0,2.3,66444.0,123.1
3,1003,AL,"Baldwin County, AL",3.0,2.0,1.0,69979.0,67370.0,2609.0,3.7,...,99953.0,97034.0,2919.0,2.9,102849.0,100432.0,2417.0,2.4,65658.0,121.6
4,1005,AL,"Barbour County, AL",6.0,6.0,0.0,11449.0,10812.0,637.0,5.6,...,8280.0,7821.0,459.0,5.5,8241.0,7906.0,335.0,4.1,38649.0,71.6

In [3]:
# computing number of rows
rows = len(df.axes[0])
# computing number of columns
cols = len(df.axes[1])
# computing the size of the dataframe
values = df.size
print("Number of Rows: ", rows)
print("Number of Columns: ", cols)
print("Number of values: ", values)

Number of Rows:  3277
Number of Columns:  100
Number of values:  327700

In [4]:
#Check the list of column names to have a better understanding of the data
columns = list(df.columns)
columns

['FIPS_Code',
 'State',
 'Area_Name',
 'Rural_Urban_Continuum_Code_2013',
 'Urban_Influence_Code_2013',
 'Metro_2013',
 'Civilian_labor_force_2000',
 'Employed_2000',
 'Unemployed_2000',
 'Unemployment_rate_2000',
 'Civilian_labor_force_2001',
 'Employed_2001',
 'Unemployed_2001',
 'Unemployment_rate_2001',
 'Civilian_labor_force_2002',
 'Employed_2002',
 'Unemployed_2002',
 'Unemployment_rate_2002',
 'Civilian_labor_force_2003',
 'Employed_2003',
 'Unemployed_2003',
 'Unemployment_rate_2003',
 'Civilian_labor_force_2004',
 'Employed_2004',
 'Unemployed_2004',
 'Unemployment_rate_2004',
 'Civilian_labor_force_2005',
 'Employed_2005',
 'Unemployed_2005',
 'Unemployment_rate_2005',
 'Civilian_labor_force_2006',
 'Employed_2006',
 'Unemployed_2006',
 'Unemployment_rate_2006',
 'Civilian_labor_force_2007',
 'Employed_2007',
 'Unemployed_2007',
 'Unemployment_rate_2007',
 'Civilian_labor_force_2008',
 'Employed_2008',
 'Unemployed_2008',
 'Unemployment_rate_2008',
 'Civilian_labor_force_2009',
 'Employed_2009',
 'Unemployed_2009',
 'Unemployment_rate_2009',
 'Civilian_labor_force_2010',
 'Employed_2010',
 'Unemployed_2010',
 'Unemployment_rate_2010',
 'Civilian_labor_force_2011',
 'Employed_2011',
 'Unemployed_2011',
 'Unemployment_rate_2011',
 'Civilian_labor_force_2012',
 'Employed_2012',
 'Unemployed_2012',
 'Unemployment_rate_2012',
 'Civilian_labor_force_2013',
 'Employed_2013',
 'Unemployed_2013',
 'Unemployment_rate_2013',
 'Civilian_labor_force_2014',
 'Employed_2014',
 'Unemployed_2014',
 'Unemployment_rate_2014',
 'Civilian_labor_force_2015',
 'Employed_2015',
 'Unemployed_2015',
 'Unemployment_rate_2015',
 'Civilian_labor_force_2016',
 'Employed_2016',
 'Unemployed_2016',
 'Unemployment_rate_2016',
 'Civilian_labor_force_2017',
 'Employed_2017',
 'Unemployed_2017',
 'Unemployment_rate_2017',
 'Civilian_labor_force_2018',
 'Employed_2018',
 'Unemployed_2018',
 'Unemployment_rate_2018',
 'Civilian_labor_force_2019',
 'Employed_2019',
 'Unemployed_2019',
 'Unemployment_rate_2019',
 'Civilian_labor_force_2020',
 'Employed_2020',
 'Unemployed_2020',
 'Unemployment_rate_2020',
 'Civilian_labor_force_2021',
 'Employed_2021',
 'Unemployed_2021',
 'Unemployment_rate_2021',
 'Civilian_labor_force_2022',
 'Employed_2022',
 'Unemployed_2022',
 'Unemployment_rate_2022',
 'Median_Household_Income_2021',
 'Med_HH_Income_Percent_of_State_Total_2021']

In [5]:
#Check if the data types are correct
print("Column datatypes: ")
print(df.dtypes)

Column datatypes:
FIPS_Code                                      int64
State                                         object
Area_Name                                     object
Rural_Urban_Continuum_Code_2013              float64
Urban_Influence_Code_2013                    float64
                                              ...
Employed_2022                                float64
Unemployed_2022                              float64
Unemployment_rate_2022                       float64
Median_Household_Income_2021                 float64
Med_HH_Income_Percent_of_State_Total_2021    float64
Length: 100, dtype: object

In [6]:
#We are only interested in the statistics from year 2013 to 2019.
#Therefore, Pull out the data within the year range and drop the rest.
df=df.drop(columns=['FIPS_Code','Rural_Urban_Continuum_Code_2013','Urban_Influence_Code_2013','Metro_2013','Civilian_labor_force_2000',
 'Employed_2000','Unemployed_2000','Unemployment_rate_2000','Civilian_labor_force_2001','Employed_2001','Unemployed_2001',
 'Unemployment_rate_2001','Civilian_labor_force_2002','Employed_2002','Unemployed_2002','Unemployment_rate_2002','Civilian_labor_force_2003',
 'Employed_2003','Unemployed_2003','Unemployment_rate_2003','Civilian_labor_force_2004','Employed_2004','Unemployed_2004',
 'Unemployment_rate_2004','Civilian_labor_force_2005','Employed_2005','Unemployed_2005','Unemployment_rate_2005',
 'Civilian_labor_force_2006','Employed_2006','Unemployed_2006','Unemployment_rate_2006','Civilian_labor_force_2007',
 'Employed_2007','Unemployed_2007','Unemployment_rate_2007','Civilian_labor_force_2008','Employed_2008','Unemployed_2008',
 'Unemployment_rate_2008','Civilian_labor_force_2009','Employed_2009','Unemployed_2009','Unemployment_rate_2009',
 'Civilian_labor_force_2010','Employed_2010','Unemployed_2010','Unemployment_rate_2010','Civilian_labor_force_2011','Employed_2011',
 'Unemployed_2011','Unemployment_rate_2011','Civilian_labor_force_2012','Employed_2012','Unemployed_2012','Unemployment_rate_2012','Civilian_labor_force_2020',
 'Employed_2020','Unemployed_2020','Unemployment_rate_2020','Civilian_labor_force_2021','Employed_2021','Unemployed_2021',
 'Unemployment_rate_2021','Civilian_labor_force_2022','Employed_2022','Unemployed_2022','Unemployment_rate_2022','Median_Household_Income_2021',
 'Med_HH_Income_Percent_of_State_Total_2021'])
df

,State,Area_Name,Civilian_labor_force_2013,Employed_2013,Unemployed_2013,Unemployment_rate_2013,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,...,Unemployed_2017,Unemployment_rate_2017,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,Unemployment_rate_2019
0,US,United States,155362278.0,143905037.0,11457241.0,7.4,155936159.0,146318952.0,9617207.0,6.2,...,7000411.0,4.4,162039448.0,155727509.0,6311939.0,3.9,163815888.0,157805898.0,6009990.0,3.7
1,AL,Alabama,2172102.0,2012828.0,159274.0,7.3,2164715.0,2018705.0,146010.0,6.7,...,99585.0,4.5,2240109.0,2152270.0,87839.0,3.9,2272935.0,2200437.0,72498.0,3.2
2,AL,"Autauga County, AL",25783.0,24155.0,1628.0,6.3,25639.0,24150.0,1489.0,5.8,...,1045.0,4.0,26471.0,25515.0,956.0,3.6,26696.0,25927.0,769.0,2.9
3,AL,"Baldwin County, AL",85206.0,79466.0,5740.0,6.7,86546.0,81265.0,5281.0,6.1,...,3866.0,4.2,96235.0,92734.0,3501.0,3.6,98965.0,96069.0,2896.0,2.9
4,AL,"Barbour County, AL",9096.0,8152.0,944.0,10.4,8859.0,7930.0,929.0,10.5,...,501.0,6.0,8505.0,8068.0,437.0,5.1,8641.0,8294.0,347.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3272,PR,"Vega Baja Municipio, PR",14601.0,12198.0,2403.0,16.5,14157.0,11869.0,2288.0,16.2,...,1668.0,12.4,13159.0,11787.0,1372.0,10.4,13174.0,11912.0,1262.0,9.6
3273,PR,"Vieques Municipio, PR",3080.0,2589.0,491.0,15.9,3152.0,2710.0,442.0,14.0,...,438.0,14.5,2726.0,2276.0,450.0,16.5,2551.0,2368.0,183.0,7.2
3274,PR,"Villalba Municipio, PR",8184.0,6416.0,1768.0,21.6,7920.0,6196.0,1724.0,21.8,...,1467.0,19.4,7335.0,6174.0,1161.0,15.8,7494.0,6309.0,1185.0,15.8
3275,PR,"Yabucoa Municipio, PR",10169.0,7742.0,2427.0,23.9,9642.0,7546.0,2096.0,21.7,...,1488.0,16.5,8791.0,7534.0,1257.0,14.3,8841.0,7686.0,1155.0,13.1
3276,PR,"Yauco Municipio, PR",11350.0,8959.0,2391.0,21.1,11031.0,8665.0,2366.0,21.4,...,1751.0,17.2,9748.0,8315.0,1433.0,14.7,9851.0,8409.0,1442.0,14.6

In [7]:
#We aim at investigating state statistics
#Detail emoployment distribution in different counties under the states does not contribute towards our project
#Therefore, we only save the rows with state names contained in the list
#Unnecessary rows describing the county are dropped

state_full=['Alabama','Alaska','American Samoa','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','District of Columbia','Federated States of Micronesia','Florida','Georgia','Guam','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Marshall Islands','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Northern Mariana Islands','Ohio','Oklahoma','Oregon','Palau','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virgin Island','Virginia','Washington','West Virginia','Wisconsin','Wyoming']
df = df[df['Area_Name'].isin(state_full)]
df

,State,Area_Name,Civilian_labor_force_2013,Employed_2013,Unemployed_2013,Unemployment_rate_2013,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,...,Unemployed_2017,Unemployment_rate_2017,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,Unemployment_rate_2019
1,AL,Alabama,2172102.0,2012828.0,159274.0,7.3,2164715.0,2018705.0,146010.0,6.7,...,99585.0,4.5,2240109.0,2152270.0,87839.0,3.9,2272935.0,2200437.0,72498.0,3.2
69,AK,Alaska,363544.0,338104.0,25440.0,7.0,364281.0,339704.0,24577.0,6.7,...,23481.0,6.5,355499.0,334068.0,21431.0,6.0,353161.0,333360.0,19801.0,5.6
104,AZ,Arizona,3064554.0,2825341.0,239213.0,7.8,3118441.0,2906193.0,212248.0,6.8,...,160411.0,5.0,3325721.0,3166013.0,159708.0,4.8,3430766.0,3265708.0,165058.0,4.8
120,AR,Arkansas,1331609.0,1237609.0,94000.0,7.1,1327959.0,1249766.0,78193.0,5.9,...,50234.0,3.7,1343862.0,1294809.0,49053.0,3.7,1354936.0,1307510.0,47426.0,3.5
196,CA,California,18565408.0,16887864.0,1677544.0,9.0,18676692.0,17264518.0,1412174.0,7.6,...,927302.0,4.8,19289505.0,18469910.0,819595.0,4.2,19413244.0,18617933.0,795311.0,4.1
255,CO,Colorado,2766140.0,2579568.0,186572.0,6.7,2800666.0,2661070.0,139596.0,5.0,...,77810.0,2.6,3054347.0,2961423.0,92924.0,3.0,3105584.0,3022829.0,82755.0,2.7
320,CT,Connecticut,1867378.0,1718834.0,148544.0,8.0,1889102.0,1764118.0,124984.0,6.6,...,84878.0,4.4,1923872.0,1849370.0,74502.0,3.9,1938637.0,1868767.0,69870.0,3.6
329,DE,Delaware,443551.0,414215.0,29336.0,6.6,452712.0,427400.0,25312.0,5.6,...,21265.0,4.5,480371.0,462545.0,17826.0,3.7,484657.0,467162.0,17495.0,3.6
333,DC,District of Columbia,374199.0,342609.0,31590.0,8.4,379678.0,350415.0,29263.0,7.7,...,23938.0,6.1,395604.0,373202.0,22402.0,5.7,399857.0,377800.0,22057.0,5.5
334,DC,District of Columbia,374199.0,342609.0,31590.0,8.4,379678.0,350415.0,29263.0,7.7,...,23938.0,6.1,395604.0,373202.0,22402.0,5.7,399857.0,377800.0,22057.0,5.5
335,FL,Florida,9414664.0,8706060.0,708604.0,7.5,9546407.0,8931440.0,614967.0,6.4,...,428098.0,4.3,10118306.0,9749598.0,368708.0,3.6,10284663.0,9950515.0,334148.0,3.2
403,GA,Georgia,4750046.0,4363292.0,386754.0,8.1,4745859.0,4407067.0,338792.0,7.1,...,243076.0,4.8,5126923.0,4922489.0,204434.0,4.0,5160512.0,4975975.0,184537.0,3.6
563,HI,Hawaii,650978.0,620005.0,30973.0,4.8,664014.0,635913.0,28101.0,4.2,...,15438.0,2.2,692457.0,675849.0,16608.0,2.4,686123.0,668774.0,17349.0,2.5
568,ID,Idaho,777606.0,724545.0,53061.0,6.8,776937.0,742805.0,34132.0,4.4,...,26901.0,3.2,862434.0,837767.0,24667.0,2.9,888504.0,862981.0,25523.0,2.9
613,IL,Illinois,6556593.0,5961201.0,595392.0,9.1,6516372.0,6049059.0,467313.0,7.2,...,324358.0,4.9,6557416.0,6270844.0,286572.0,4.4,6550295.0,6289513.0,260782.0,4.0
716,IN,Indiana,3193683.0,2953672.0,240011.0,7.5,3228524.0,3036685.0,191839.0,5.9,...,116644.0,3.5,3392579.0,3276805.0,115774.0,3.4,3404321.0,3291950.0,112371.0,3.3
809,IA,Iowa,1676565.0,1597139.0,79426.0,4.7,1698718.0,1626676.0,72042.0,4.2,...,51835.0,3.1,1711811.0,1667817.0,43994.0,2.6,1743153.0,1696691.0,46462.0,2.7
909,KS,Kansas,1489395.0,1410470.0,78925.0,5.3,1494203.0,1426892.0,67311.0,4.5,...,53830.0,3.6,1493360.0,1443204.0,50156.0,3.4,1504552.0,1455263.0,49289.0,3.3
1015,KY,Kentucky,2055895.0,1892777.0,163118.0,7.9,2006518.0,1877551.0,128967.0,6.4,...,98164.0,4.8,2052877.0,1966186.0,86691.0,4.2,2068975.0,1983872.0,85103.0,4.1
1136,LA,Louisiana,2101974.0,1966755.0,135219.0,6.4,2141519.0,2007668.0,133851.0,6.3,...,107998.0,5.1,2109741.0,2007981.0,101760.0,4.8,2105926.0,2008163.0,97763.0,4.6
1201,ME,Maine,704240.0,657058.0,47182.0,6.7,698035.0,659008.0,39027.0,5.6,...,23707.0,3.4,700856.0,678584.0,22272.0,3.2,697795.0,677460.0,20335.0,2.9
1218,MD,Maryland,3128908.0,2924626.0,204282.0,6.5,3125017.0,2945911.0,179106.0,5.7,...,129316.0,4.0,3270635.0,3146485.0,124150.0,3.8,3334365.0,3221317.0,113048.0,3.4
1243,MA,Massachusetts,3516689.0,3283144.0,233545.0,6.6,3569557.0,3364853.0,204704.0,5.7,...,142131.0,3.8,3818769.0,3686198.0,132571.0,3.5,3841324.0,3725143.0,116181.0,3.0
1258,MI,Michigan,4736919.0,4323410.0,413509.0,8.7,4759720.0,4416017.0,343703.0,7.2,...,225394.0,4.6,4944794.0,4739081.0,205713.0,4.2,4976013.0,4773453.0,202560.0,4.1
1342,MN,Minnesota,2961729.0,2812453.0,149276.0,5.0,2979798.0,2852488.0,127310.0,4.3,...,107176.0,3.5,3075090.0,2982658.0,92432.0,3.0,3108682.0,3007374.0,101308.0,3.3
1430,MS,Mississippi,1273057.0,1164832.0,108225.0,8.5,1243934.0,1149277.0,94657.0,7.6,...,66583.0,5.2,1268040.0,1205342.0,62698.0,4.9,1278598.0,1208096.0,70502.0,5.5
1513,MO,Missouri,3011198.0,2807115.0,204083.0,6.8,3035599.0,2848571.0,187028.0,6.2,...,114220.0,3.7,3048449.0,2949963.0,98486.0,3.2,3074821.0,2975703.0,99118.0,3.2
1629,MT,Montana,511199.0,483798.0,27401.0,5.4,512613.0,488738.0,23875.0,4.7,...,21570.0,4.1,535140.0,515213.0,19927.0,3.7,543741.0,524686.0,19055.0,3.5
1686,NE,Nebraska,1014830.0,977464.0,37366.0,3.7,1012727.0,979728.0,32999.0,3.3,...,30423.0,3.0,1036411.0,1006283.0,30128.0,2.9,1051554.0,1018707.0,32847.0,3.1
1780,NV,Nevada,1370727.0,1234021.0,136706.0,10.0,1380084.0,1267424.0,112660.0,8.2,...,72240.0,5.0,1494692.0,1429284.0,65408.0,4.4,1546313.0,1482647.0,63666.0,4.1
1798,NH,New Hampshire,743036.0,704023.0,39013.0,5.3,743756.0,711740.0,32016.0,4.3,...,21215.0,2.8,770469.0,750285.0,20184.0,2.6,780540.0,760516.0,20024.0,2.6
1809,NJ,New Jersey,4528019.0,4147661.0,380358.0,8.4,4493894.0,4191318.0,302576.0,6.7,...,208802.0,4.5,4604787.0,4420713.0,184074.0,4.0,4686262.0,4524292.0,161970.0,3.5
1831,NM,New Mexico,929410.0,865207.0,64203.0,6.9,931950.0,870570.0,61380.0,6.6,...,57593.0,6.1,944936.0,898360.0,46576.0,4.9,956094.0,908703.0,47391.0,5.0
1865,NY,New York,9632949.0,8880792.0,752157.0,7.8,9523567.0,8925328.0,598239.0,6.3,...,455420.0,4.6,9826126.0,9424212.0,401914.0,4.1,9853962.0,9474510.0,379452.0,3.9
1928,NC,North Carolina,4701391.0,4336379.0,365012.0,7.8,4698287.0,4410647.0,287640.0,6.1,...,219688.0,4.5,4911884.0,4715616.0,196268.0,4.0,4993476.0,4801094.0,192382.0,3.9
2029,ND,North Dakota,401518.0,389928.0,11590.0,2.9,409503.0,398783.0,10720.0,2.6,...,10864.0,2.6,412069.0,402201.0,9868.0,2.4,413845.0,404793.0,9052.0,2.2
2083,OH,Ohio,5706777.0,5281459.0,425318.0,7.5,5713176.0,5381787.0,331389.0,5.8,...,289496.0,5.0,5819989.0,5558124.0,261865.0,4.5,5877451.0,5632572.0,244879.0,4.2
2172,OK,Oklahoma,1799525.0,1707220.0,92305.0,5.1,1797769.0,1719826.0,77943.0,4.3,...,73539.0,4.0,1831256.0,1771251.0,60005.0,3.3,1840223.0,1782411.0,57812.0,3.1
2250,OR,Oregon,1924692.0,1775139.0,149553.0,7.8,1950128.0,1820202.0,129926.0,6.7,...,84179.0,4.1,2080051.0,1996490.0,83561.0,4.0,2094783.0,2017199.0,77584.0,3.7
2287,PA,Pennsylvania,6419837.0,5962130.0,457707.0,7.1,6389059.0,6010075.0,378984.0,5.9,...,323340.0,5.0,6509775.0,6222004.0,287771.0,4.4,6573616.0,6287804.0,285812.0,4.3
2355,RI,Rhode Island,558747.0,505776.0,52971.0,9.5,556635.0,513406.0,43229.0,7.8,...,25592.0,4.5,572663.0,549529.0,23134.0,4.0,574346.0,554076.0,20270.0,3.5
2361,SC,South Carolina,2197876.0,2034404.0,163472.0,7.4,2222426.0,2082941.0,139485.0,6.3,...,95058.0,4.2,2282022.0,2205356.0,76666.0,3.4,2324500.0,2259807.0,64693.0,2.8
2408,SD,South Dakota,447479.0,430834.0,16645.0,3.7,450769.0,435733.0,15036.0,3.3,...,13889.0,3.1,459202.0,446413.0,12789.0,2.8,464329.0,451353.0,12976.0,2.8
2475,TN,Tennessee,3078892.0,2840127.0,238765.0,7.8,3043573.0,2842540.0,201033.0,6.6,...,119517.0,3.7,3257053.0,3143792.0,113261.0,3.5,3335270.0,3223664.0,111606.0,3.3
2571,TX,Texas,12832035.0,12022272.0,809763.0,6.3,13006202.0,12333076.0,673126.0,5.2,...,585966.0,4.3,13714126.0,13178793.0,535333.0,3.9,13921781.0,13429073.0,492708.0,3.5
2826,UT,Utah,1385908.0,1327560.0,58348.0,4.2,1415779.0,1364353.0,51426.0,3.6,...,48939.0,3.1,1584494.0,1538295.0,46199.0,2.9,1618697.0,1577591.0,41106.0,2.5
2856,VT,Vermont,350175.0,334684.0,15491.0,4.4,348697.0,334742.0,13955.0,4.0,...,10687.0,3.0,355343.0,346553.0,8790.0,2.5,353506.0,346016.0,7490.0,2.1
2871,VA,Virginia,4238377.0,4002057.0,236320.0,5.6,4258856.0,4040908.0,217948.0,5.1,...,159687.0,3.7,4359053.0,4228274.0,130779.0,3.0,4414972.0,4292501.0,122471.0,2.8
3005,WA,Washington,3460772.0,3230947.0,229825.0,6.6,3495153.0,3287904.0,207249.0,5.9,...,172929.0,4.6,3814538.0,3645992.0,168546.0,4.4,3933880.0,3766964.0,166916.0,4.2
3045,WV,West Virginia,799481.0,745849.0,53632.0,6.7,795733.0,743955.0,51778.0,6.5,...,40958.0,5.2,793415.0,752602.0,40813.0,5.1,795299.0,755909.0,39390.0,5.0
3101,WI,Wisconsin,3077801.0,2871988.0,205813.0,6.7,3077981.0,2913764.0,164217.0,5.3,...,102409.0,3.3,3123898.0,3030659.0,93239.0,3.0,3111729.0,3012828.0,98901.0,3.2
3174,WY,Wyoming,302201.0,287792.0,14409.0,4.8,302865.0,289694.0,13171.0,4.3,...,12638.0,4.3,292629.0,280754.0,11875.0,4.1,293320.0,282433.0,10887.0,3.7

In [8]:
#Check if there are duplicate rows and drop them if there are any
df=df.drop_duplicates()
df

,State,Area_Name,Civilian_labor_force_2013,Employed_2013,Unemployed_2013,Unemployment_rate_2013,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,...,Unemployed_2017,Unemployment_rate_2017,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Civilian_labor_force_2019,Employed_2019,Unemployed_2019,Unemployment_rate_2019
1,AL,Alabama,2172102.0,2012828.0,159274.0,7.3,2164715.0,2018705.0,146010.0,6.7,...,99585.0,4.5,2240109.0,2152270.0,87839.0,3.9,2272935.0,2200437.0,72498.0,3.2
69,AK,Alaska,363544.0,338104.0,25440.0,7.0,364281.0,339704.0,24577.0,6.7,...,23481.0,6.5,355499.0,334068.0,21431.0,6.0,353161.0,333360.0,19801.0,5.6
104,AZ,Arizona,3064554.0,2825341.0,239213.0,7.8,3118441.0,2906193.0,212248.0,6.8,...,160411.0,5.0,3325721.0,3166013.0,159708.0,4.8,3430766.0,3265708.0,165058.0,4.8
120,AR,Arkansas,1331609.0,1237609.0,94000.0,7.1,1327959.0,1249766.0,78193.0,5.9,...,50234.0,3.7,1343862.0,1294809.0,49053.0,3.7,1354936.0,1307510.0,47426.0,3.5
196,CA,California,18565408.0,16887864.0,1677544.0,9.0,18676692.0,17264518.0,1412174.0,7.6,...,927302.0,4.8,19289505.0,18469910.0,819595.0,4.2,19413244.0,18617933.0,795311.0,4.1
255,CO,Colorado,2766140.0,2579568.0,186572.0,6.7,2800666.0,2661070.0,139596.0,5.0,...,77810.0,2.6,3054347.0,2961423.0,92924.0,3.0,3105584.0,3022829.0,82755.0,2.7
320,CT,Connecticut,1867378.0,1718834.0,148544.0,8.0,1889102.0,1764118.0,124984.0,6.6,...,84878.0,4.4,1923872.0,1849370.0,74502.0,3.9,1938637.0,1868767.0,69870.0,3.6
329,DE,Delaware,443551.0,414215.0,29336.0,6.6,452712.0,427400.0,25312.0,5.6,...,21265.0,4.5,480371.0,462545.0,17826.0,3.7,484657.0,467162.0,17495.0,3.6
333,DC,District of Columbia,374199.0,342609.0,31590.0,8.4,379678.0,350415.0,29263.0,7.7,...,23938.0,6.1,395604.0,373202.0,22402.0,5.7,399857.0,377800.0,22057.0,5.5
335,FL,Florida,9414664.0,8706060.0,708604.0,7.5,9546407.0,8931440.0,614967.0,6.4,...,428098.0,4.3,10118306.0,9749598.0,368708.0,3.6,10284663.0,9950515.0,334148.0,3.2
403,GA,Georgia,4750046.0,4363292.0,386754.0,8.1,4745859.0,4407067.0,338792.0,7.1,...,243076.0,4.8,5126923.0,4922489.0,204434.0,4.0,5160512.0,4975975.0,184537.0,3.6
563,HI,Hawaii,650978.0,620005.0,30973.0,4.8,664014.0,635913.0,28101.0,4.2,...,15438.0,2.2,692457.0,675849.0,16608.0,2.4,686123.0,668774.0,17349.0,2.5
568,ID,Idaho,777606.0,724545.0,53061.0,6.8,776937.0,742805.0,34132.0,4.4,...,26901.0,3.2,862434.0,837767.0,24667.0,2.9,888504.0,862981.0,25523.0,2.9
613,IL,Illinois,6556593.0,5961201.0,595392.0,9.1,6516372.0,6049059.0,467313.0,7.2,...,324358.0,4.9,6557416.0,6270844.0,286572.0,4.4,6550295.0,6289513.0,260782.0,4.0
716,IN,Indiana,3193683.0,2953672.0,240011.0,7.5,3228524.0,3036685.0,191839.0,5.9,...,116644.0,3.5,3392579.0,3276805.0,115774.0,3.4,3404321.0,3291950.0,112371.0,3.3
809,IA,Iowa,1676565.0,1597139.0,79426.0,4.7,1698718.0,1626676.0,72042.0,4.2,...,51835.0,3.1,1711811.0,1667817.0,43994.0,2.6,1743153.0,1696691.0,46462.0,2.7
909,KS,Kansas,1489395.0,1410470.0,78925.0,5.3,1494203.0,1426892.0,67311.0,4.5,...,53830.0,3.6,1493360.0,1443204.0,50156.0,3.4,1504552.0,1455263.0,49289.0,3.3
1015,KY,Kentucky,2055895.0,1892777.0,163118.0,7.9,2006518.0,1877551.0,128967.0,6.4,...,98164.0,4.8,2052877.0,1966186.0,86691.0,4.2,2068975.0,1983872.0,85103.0,4.1
1136,LA,Louisiana,2101974.0,1966755.0,135219.0,6.4,2141519.0,2007668.0,133851.0,6.3,...,107998.0,5.1,2109741.0,2007981.0,101760.0,4.8,2105926.0,2008163.0,97763.0,4.6
1201,ME,Maine,704240.0,657058.0,47182.0,6.7,698035.0,659008.0,39027.0,5.6,...,23707.0,3.4,700856.0,678584.0,22272.0,3.2,697795.0,677460.0,20335.0,2.9
1218,MD,Maryland,3128908.0,2924626.0,204282.0,6.5,3125017.0,2945911.0,179106.0,5.7,...,129316.0,4.0,3270635.0,3146485.0,124150.0,3.8,3334365.0,3221317.0,113048.0,3.4
1243,MA,Massachusetts,3516689.0,3283144.0,233545.0,6.6,3569557.0,3364853.0,204704.0,5.7,...,142131.0,3.8,3818769.0,3686198.0,132571.0,3.5,3841324.0,3725143.0,116181.0,3.0
1258,MI,Michigan,4736919.0,4323410.0,413509.0,8.7,4759720.0,4416017.0,343703.0,7.2,...,225394.0,4.6,4944794.0,4739081.0,205713.0,4.2,4976013.0,4773453.0,202560.0,4.1
1342,MN,Minnesota,2961729.0,2812453.0,149276.0,5.0,2979798.0,2852488.0,127310.0,4.3,...,107176.0,3.5,3075090.0,2982658.0,92432.0,3.0,3108682.0,3007374.0,101308.0,3.3
1430,MS,Mississippi,1273057.0,1164832.0,108225.0,8.5,1243934.0,1149277.0,94657.0,7.6,...,66583.0,5.2,1268040.0,1205342.0,62698.0,4.9,1278598.0,1208096.0,70502.0,5.5
1513,MO,Missouri,3011198.0,2807115.0,204083.0,6.8,3035599.0,2848571.0,187028.0,6.2,...,114220.0,3.7,3048449.0,2949963.0,98486.0,3.2,3074821.0,2975703.0,99118.0,3.2
1629,MT,Montana,511199.0,483798.0,27401.0,5.4,512613.0,488738.0,23875.0,4.7,...,21570.0,4.1,535140.0,515213.0,19927.0,3.7,543741.0,524686.0,19055.0,3.5
1686,NE,Nebraska,1014830.0,977464.0,37366.0,3.7,1012727.0,979728.0,32999.0,3.3,...,30423.0,3.0,1036411.0,1006283.0,30128.0,2.9,1051554.0,1018707.0,32847.0,3.1
1780,NV,Nevada,1370727.0,1234021.0,136706.0,10.0,1380084.0,1267424.0,112660.0,8.2,...,72240.0,5.0,1494692.0,1429284.0,65408.0,4.4,1546313.0,1482647.0,63666.0,4.1
1798,NH,New Hampshire,743036.0,704023.0,39013.0,5.3,743756.0,711740.0,32016.0,4.3,...,21215.0,2.8,770469.0,750285.0,20184.0,2.6,780540.0,760516.0,20024.0,2.6
1809,NJ,New Jersey,4528019.0,4147661.0,380358.0,8.4,4493894.0,4191318.0,302576.0,6.7,...,208802.0,4.5,4604787.0,4420713.0,184074.0,4.0,4686262.0,4524292.0,161970.0,3.5
1831,NM,New Mexico,929410.0,865207.0,64203.0,6.9,931950.0,870570.0,61380.0,6.6,...,57593.0,6.1,944936.0,898360.0,46576.0,4.9,956094.0,908703.0,47391.0,5.0
1865,NY,New York,9632949.0,8880792.0,752157.0,7.8,9523567.0,8925328.0,598239.0,6.3,...,455420.0,4.6,9826126.0,9424212.0,401914.0,4.1,9853962.0,9474510.0,379452.0,3.9
1928,NC,North Carolina,4701391.0,4336379.0,365012.0,7.8,4698287.0,4410647.0,287640.0,6.1,...,219688.0,4.5,4911884.0,4715616.0,196268.0,4.0,4993476.0,4801094.0,192382.0,3.9
2029,ND,North Dakota,401518.0,389928.0,11590.0,2.9,409503.0,398783.0,10720.0,2.6,...,10864.0,2.6,412069.0,402201.0,9868.0,2.4,413845.0,404793.0,9052.0,2.2
2083,OH,Ohio,5706777.0,5281459.0,425318.0,7.5,5713176.0,5381787.0,331389.0,5.8,...,289496.0,5.0,5819989.0,5558124.0,261865.0,4.5,5877451.0,5632572.0,244879.0,4.2
2172,OK,Oklahoma,1799525.0,1707220.0,92305.0,5.1,1797769.0,1719826.0,77943.0,4.3,...,73539.0,4.0,1831256.0,1771251.0,60005.0,3.3,1840223.0,1782411.0,57812.0,3.1
2250,OR,Oregon,1924692.0,1775139.0,149553.0,7.8,1950128.0,1820202.0,129926.0,6.7,...,84179.0,4.1,2080051.0,1996490.0,83561.0,4.0,2094783.0,2017199.0,77584.0,3.7
2287,PA,Pennsylvania,6419837.0,5962130.0,457707.0,7.1,6389059.0,6010075.0,378984.0,5.9,...,323340.0,5.0,6509775.0,6222004.0,287771.0,4.4,6573616.0,6287804.0,285812.0,4.3
2355,RI,Rhode Island,558747.0,505776.0,52971.0,9.5,556635.0,513406.0,43229.0,7.8,...,25592.0,4.5,572663.0,549529.0,23134.0,4.0,574346.0,554076.0,20270.0,3.5
2361,SC,South Carolina,2197876.0,2034404.0,163472.0,7.4,2222426.0,2082941.0,139485.0,6.3,...,95058.0,4.2,2282022.0,2205356.0,76666.0,3.4,2324500.0,2259807.0,64693.0,2.8
2408,SD,South Dakota,447479.0,430834.0,16645.0,3.7,450769.0,435733.0,15036.0,3.3,...,13889.0,3.1,459202.0,446413.0,12789.0,2.8,464329.0,451353.0,12976.0,2.8
2475,TN,Tennessee,3078892.0,2840127.0,238765.0,7.8,3043573.0,2842540.0,201033.0,6.6,...,119517.0,3.7,3257053.0,3143792.0,113261.0,3.5,3335270.0,3223664.0,111606.0,3.3
2571,TX,Texas,12832035.0,12022272.0,809763.0,6.3,13006202.0,12333076.0,673126.0,5.2,...,585966.0,4.3,13714126.0,13178793.0,535333.0,3.9,13921781.0,13429073.0,492708.0,3.5
2826,UT,Utah,1385908.0,1327560.0,58348.0,4.2,1415779.0,1364353.0,51426.0,3.6,...,48939.0,3.1,1584494.0,1538295.0,46199.0,2.9,1618697.0,1577591.0,41106.0,2.5
2856,VT,Vermont,350175.0,334684.0,15491.0,4.4,348697.0,334742.0,13955.0,4.0,...,10687.0,3.0,355343.0,346553.0,8790.0,2.5,353506.0,346016.0,7490.0,2.1
2871,VA,Virginia,4238377.0,4002057.0,236320.0,5.6,4258856.0,4040908.0,217948.0,5.1,...,159687.0,3.7,4359053.0,4228274.0,130779.0,3.0,4414972.0,4292501.0,122471.0,2.8
3005,WA,Washington,3460772.0,3230947.0,229825.0,6.6,3495153.0,3287904.0,207249.0,5.9,...,172929.0,4.6,3814538.0,3645992.0,168546.0,4.4,3933880.0,3766964.0,166916.0,4.2
3045,WV,West Virginia,799481.0,745849.0,53632.0,6.7,795733.0,743955.0,51778.0,6.5,...,40958.0,5.2,793415.0,752602.0,40813.0,5.1,795299.0,755909.0,39390.0,5.0
3101,WI,Wisconsin,3077801.0,2871988.0,205813.0,6.7,3077981.0,2913764.0,164217.0,5.3,...,102409.0,3.3,3123898.0,3030659.0,93239.0,3.0,3111729.0,3012828.0,98901.0,3.2
3174,WY,Wyoming,302201.0,287792.0,14409.0,4.8,302865.0,289694.0,13171.0,4.3,...,12638.0,4.3,292629.0,280754.0,11875.0,4.1,293320.0,282433.0,10887.0,3.7

In [9]:
#Check if there are missing values
print("Missing values distribution: ")
print(df.isnull().mean())
print("")

Missing values distribution:
State                        0.0
Area_Name                    0.0
Civilian_labor_force_2013    0.0
Employed_2013                0.0
Unemployed_2013              0.0
Unemployment_rate_2013       0.0
Civilian_labor_force_2014    0.0
Employed_2014                0.0
Unemployed_2014              0.0
Unemployment_rate_2014       0.0
Civilian_labor_force_2015    0.0
Employed_2015                0.0
Unemployed_2015              0.0
Unemployment_rate_2015       0.0
Civilian_labor_force_2016    0.0
Employed_2016                0.0
Unemployed_2016              0.0
Unemployment_rate_2016       0.0
Civilian_labor_force_2017    0.0
Employed_2017                0.0
Unemployed_2017              0.0
Unemployment_rate_2017       0.0
Civilian_labor_force_2018    0.0
Employed_2018                0.0
Unemployed_2018              0.0
Unemployment_rate_2018       0.0
Civilian_labor_force_2019    0.0
Employed_2019                0.0
Unemployed_2019              0.0
Unemployment_rate_2019       0.0
dtype: float64

In [10]:
#Change the column names to avoid any confusion
df.columns.values[0] = "Postal Abbr."
df.columns.values[1] = "State"

In [11]:
#Now we need to convert the dataset from wide to long format so that it is easier to read
#It also provides convenience to the data integration process later on.
#The first step is to reshape the DataFrame with Pandas stack() and unstack()
df1=df[df.columns].set_index(['Postal Abbr.','State']).stack().reset_index()
df1

     Postal Abbr.    State                    level_2          0
0              AL  Alabama  Civilian_labor_force_2013  2172102.0
1              AL  Alabama              Employed_2013  2012828.0
2              AL  Alabama            Unemployed_2013   159274.0
3              AL  Alabama     Unemployment_rate_2013        7.3
4              AL  Alabama  Civilian_labor_force_2014  2164715.0
...           ...      ...                        ...        ...
1423           WY  Wyoming     Unemployment_rate_2018        4.1
1424           WY  Wyoming  Civilian_labor_force_2019   293320.0
1425           WY  Wyoming              Employed_2019   282433.0
1426           WY  Wyoming            Unemployed_2019    10887.0
1427           WY  Wyoming     Unemployment_rate_2019        3.7

[1428 rows x 4 columns]

In [12]:
#Rename relevent columns
df1=df1.rename(columns={'level_2': 'Type',0: 'Rate'} )

In [13]:
#Seperate the year from the 'Type' column using the rsplit function targeting at the last underscore
#Create a new column called 'Year' to store the data
df1[["Type","Year"]]=df1["Type"].str.rsplit("_",n=1,expand=True)
df1

     Postal Abbr.    State                  Type       Rate  Year
0              AL  Alabama  Civilian_labor_force  2172102.0  2013
1              AL  Alabama              Employed  2012828.0  2013
2              AL  Alabama            Unemployed   159274.0  2013
3              AL  Alabama     Unemployment_rate        7.3  2013
4              AL  Alabama  Civilian_labor_force  2164715.0  2014
...           ...      ...                   ...        ...   ...
1423           WY  Wyoming     Unemployment_rate        4.1  2018
1424           WY  Wyoming  Civilian_labor_force   293320.0  2019
1425           WY  Wyoming              Employed   282433.0  2019
1426           WY  Wyoming            Unemployed    10887.0  2019
1427           WY  Wyoming     Unemployment_rate        3.7  2019

[1428 rows x 5 columns]

In [14]:
#Move the columns
df1 = df1[['Postal Abbr.','State','Year','Type','Rate']]
df1['Year']=df1['Year'].astype('int')

In [15]:
#Create a pivot table using 'Postal Abbr.','State','Year' as index
df1=df1.pivot_table(index=['Postal Abbr.','State','Year'], columns='Type', values='Rate')
df1

Type                       Civilian_labor_force  Employed  Unemployed  \
Postal Abbr. State   Year
AK           Alaska  2013              363544.0  338104.0     25440.0
                     2014              364281.0  339704.0     24577.0
                     2015              362425.0  339604.0     22821.0
                     2016              362017.0  338193.0     23824.0
                     2017              360589.0  337108.0     23481.0
...                                         ...       ...         ...
WY           Wyoming 2015              301608.0  288894.0     12714.0
                     2016              300546.0  284439.0     16107.0
                     2017              293802.0  281164.0     12638.0
                     2018              292629.0  280754.0     11875.0
                     2019              293320.0  282433.0     10887.0

Type                       Unemployment_rate
Postal Abbr. State   Year
AK           Alaska  2013                7.0
                     2014                6.7
                     2015                6.3
                     2016                6.6
                     2017                6.5
...                                      ...
WY           Wyoming 2015                4.2
                     2016                5.4
                     2017                4.3
                     2018                4.1
                     2019                3.7

[357 rows x 4 columns]

In [16]:
#Remove the unnecessary heading
df1.columns.name = ' ' 
df1

                           Civilian_labor_force  Employed  Unemployed  \
Postal Abbr. State   Year
AK           Alaska  2013              363544.0  338104.0     25440.0
                     2014              364281.0  339704.0     24577.0
                     2015              362425.0  339604.0     22821.0
                     2016              362017.0  338193.0     23824.0
                     2017              360589.0  337108.0     23481.0
...                                         ...       ...         ...
WY           Wyoming 2015              301608.0  288894.0     12714.0
                     2016              300546.0  284439.0     16107.0
                     2017              293802.0  281164.0     12638.0
                     2018              292629.0  280754.0     11875.0
                     2019              293320.0  282433.0     10887.0

                           Unemployment_rate
Postal Abbr. State   Year
AK           Alaska  2013                7.0
                     2014                6.7
                     2015                6.3
                     2016                6.6
                     2017                6.5
...                                      ...
WY           Wyoming 2015                4.2
                     2016                5.4
                     2017                4.3
                     2018                4.1
                     2019                3.7

[357 rows x 4 columns]

In [17]:
#Pivot table to normal table, sorted by year.
df1=df1.sort_values(by=['State','Year'])
df1 = df1.reset_index()
df1

,Postal Abbr.,State,Year,Civilian_labor_force,Employed,Unemployed,Unemployment_rate
0,AL,Alabama,2013,2172102.0,2012828.0,159274.0,7.3
1,AL,Alabama,2014,2164715.0,2018705.0,146010.0,6.7
2,AL,Alabama,2015,2152295.0,2020443.0,131852.0,6.1
3,AL,Alabama,2016,2155729.0,2029157.0,126572.0,5.9
4,AL,Alabama,2017,2203458.0,2103873.0,99585.0,4.5
...,...,...,...,...,...,...,...
352,WY,Wyoming,2015,301608.0,288894.0,12714.0,4.2
353,WY,Wyoming,2016,300546.0,284439.0,16107.0,5.4
354,WY,Wyoming,2017,293802.0,281164.0,12638.0,4.3
355,WY,Wyoming,2018,292629.0,280754.0,11875.0,4.1
356,WY,Wyoming,2019,293320.0,282433.0,10887.0,3.7

In [18]:
#The reshaping dataframe process is completed
#Check data type again
#Check if the data types are correct
print("Column datatypes: ")
print(df1.dtypes)

Column datatypes:

Postal Abbr.             object
State                    object
Year                      int64
Civilian_labor_force    float64
Employed                float64
Unemployed              float64
Unemployment_rate       float64
dtype: object

In [19]:
#Final look of the output

df1

,Postal Abbr.,State,Year,Civilian_labor_force,Employed,Unemployed,Unemployment_rate
0,AL,Alabama,2013,2172102.0,2012828.0,159274.0,7.3
1,AL,Alabama,2014,2164715.0,2018705.0,146010.0,6.7
2,AL,Alabama,2015,2152295.0,2020443.0,131852.0,6.1
3,AL,Alabama,2016,2155729.0,2029157.0,126572.0,5.9
4,AL,Alabama,2017,2203458.0,2103873.0,99585.0,4.5
...,...,...,...,...,...,...,...
352,WY,Wyoming,2015,301608.0,288894.0,12714.0,4.2
353,WY,Wyoming,2016,300546.0,284439.0,16107.0,5.4
354,WY,Wyoming,2017,293802.0,281164.0,12638.0,4.3
355,WY,Wyoming,2018,292629.0,280754.0,11875.0,4.1
356,WY,Wyoming,2019,293320.0,282433.0,10887.0,3.7

In [20]:
#Export dataframe to Excel
df1.to_excel("/Users/wangyining/Documents/employment status/Unemployment_exported.xlsx")